Repository hmcts/pip-account-management, pull requests merged in 2023-06, with the labels that each got.

#280 PUB-1996 - Updated dependencies
  build.gradle
  charts/pip-account-management/Chart.yaml
  config/owasp/suppressions.xml
Labels: ns:pip, prd:pip, rel:pip-account-management-pr-280

#282 Suppress CVE-2023-34411
  config/owasp/suppressions.xml
Labels: ns:pip, prd:pip, rel:pip-account-management-pr-282

#283 PUB-1900 update Gradle to V8
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: ns:pip, prd:pip, rel:pip-account-management-pr-283

#285 Suppress CVE-2023-35116
  config/owasp/suppressions.xml
Labels: ns:pip, prd:pip, rel:pip-account-management-pr-285
