Repository hmcts/pip-account-management, pull requests merged in 2023-11, with the labels that each got.

#369 PUB-2222 - Removed old config
  infrastructure/providers.tf
  infrastructure/tf-db-flexible.tf
  infrastructure/tf-db-main.tf
Labels: ns:pip, prd:pip, add-or-update, rel:pip-account-management-pr-369

#370 PUB-2222 - Remove old postgres
  infrastructure/tf-db-flexible-secrets.tf
  infrastructure/tf-db-secrets.tf
Labels: ns:pip, prd:pip, add-or-update, rel:pip-account-management-pr-370

#372 PUB-2222 - Removed old postgres
  infrastructure/tf-db-main.tf
Labels: ns:pip, prd:pip, add-or-update, rel:pip-account-management-pr-372

#373 PUB-2222 - Removed ITHC + Staging
  infrastructure/tf-db-main.tf
Labels: ns:pip, prd:pip, destroy, rel:pip-account-management-pr-373

#376 PUB-2222 - Updated permissions
  infrastructure/tf-db-flexible.tf
Labels: ns:pip, prd:pip, destroy, rel:pip-account-management-pr-376

#368 PUB-2153 Add OPA Press List listType
  build.gradle
Labels: ns:pip, prd:pip, rel:pip-account-management-pr-368

#375 PUB-2222 - Removed old postgres
  infrastructure/tf-db-main.tf
Labels: ns:pip, prd:pip, add-or-update, rel:pip-account-management-pr-375

#374 PUB-2222 - Removed old postgres part 2
  infrastructure/tf-db-flexible-secrets.tf
  infrastructure/tf-db-flexible.tf
  infrastructure/tf-db-main.tf
Labels: ns:pip, prd:pip, destroy, rel:pip-account-management-pr-374

#377 PUB-2206 - Dependency Updates
  build.gradle
  config/owasp/suppressions.xml
  infrastructure/.terraform-version
  infrastructure/providers.tf
Labels: ns:pip, prd:pip, add-or-update, rel:pip-account-management-pr-377
