Repository hmcts/pip-account-management, pull requests merged in 2023-10, with the labels that each got.

#346 PUB-2130 Create Postgres 15 Azure Flexible Server
  infrastructure/providers.tf
  infrastructure/tf-db-flexible-secrets.tf
  infrastructure/tf-db-flexible.tf
  infrastructure/variables.tf
Labels: ns:pip, prd:pip, add-or-update, rel:pip-account-management-pr-346

#355 PUB-2188 - Migrating lower environments
  infrastructure/providers.tf
  infrastructure/tf-db-flexible-secrets.tf
  infrastructure/tf-db-flexible.tf
  infrastructure/tf-db-main.tf
Labels: ns:pip, prd:pip, destroy, rel:pip-account-management-pr-355

#356 PUB-2188 - Migrate Lower Environments - Demo
  infrastructure/tf-db-flexible.tf
Labels: ns:pip, prd:pip, add-or-update, rel:pip-account-management-pr-356

#357 PUB-2188 - Migrate Lower Environments - Test
  infrastructure/tf-db-main.tf
Labels: ns:pip, prd:pip, add-or-update, rel:pip-account-management-pr-357

#358 PUB-2188 - Added suppression
  config/owasp/suppressions.xml
Labels: ns:pip, prd:pip, rel:pip-account-management-pr-358

#352 PUB-2162 Add authorisation check to update and delete account endpoints
  src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/AccountTest.java
  src/main/java/uk/gov/hmcts/reform/pip/account/management/controllers/AccountController.java
  src/main/java/uk/gov/hmcts/reform/pip/account/management/errorhandling/GlobalExceptionHandler.java
  src/main/java/uk/gov/hmcts/reform/pip/account/management/errorhandling/exceptions/ForbiddenRoleUpdateException.java
  src/main/java/uk/gov/hmcts/reform/pip/account/management/service/AccountService.java
  src/main/java/uk/gov/hmcts/reform/pip/account/management/service/AuthorisationService.java
  src/test/java/uk/gov/hmcts/reform/pip/account/management/controllers/AccountControllerTest.java
  src/test/java/uk/gov/hmcts/reform/pip/account/management/errorhandling/GlobalExceptionHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/pip/account/management/errorhandling/exceptions/CustomExceptionTest.java
  src/test/java/uk/gov/hmcts/reform/pip/account/management/service/AccountServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/account/management/service/AuthorisationServiceTest.java
Labels: ns:pip, prd:pip, rel:pip-account-management-pr-352

#360 PUB-2188 - Added staging
  build.gradle
  config/owasp/suppressions.xml
  infrastructure/tf-db-main.tf
Labels: ns:pip, prd:pip, destroy, rel:pip-account-management-pr-360

#361 PUB-2188 - Migrate lower environments
  charts/pip-account-management/values.stg.template.yaml
  infrastructure/tf-db-flexible.tf
Labels: ns:pip, prd:pip, add-or-update, rel:pip-account-management-pr-361

#362 PUB-2188 - Updated ITHC
  infrastructure/tf-db-main.tf
Labels: ns:pip, prd:pip, add-or-update, rel:pip-account-management-pr-362

#353 PUB-2192 - Monthly Dependency Updates
  .github/workflows/ci.yml
  build.gradle
  charts/pip-account-management/Chart.yaml
  config/owasp/suppressions.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  infrastructure/.terraform-version
  infrastructure/providers.tf
Labels: ns:pip, prd:pip, add-or-update, rel:pip-account-management-pr-353, enable_keep_helm

#364 PUB-2188 - Updated secrets
  build.gradle
  config/owasp/suppressions.xml
  infrastructure/tf-db-secrets.tf
Labels: ns:pip, prd:pip, add-or-update, rel:pip-account-management-pr-364

#365 PUB-2188 - Added staging
  charts/pip-account-management/values.stg.template.yaml
  infrastructure/tf-db-secrets.tf
Labels: ns:pip, prd:pip, add-or-update, rel:pip-account-management-pr-365

#366 PUB-2189 - Removed role
  infrastructure/tf-db-main.tf
Labels: ns:pip, prd:pip, add-or-update, rel:pip-account-management-pr-366

#367 PUB-2189 - Part 2
  infrastructure/tf-db-flexible.tf
  infrastructure/tf-db-secrets.tf
Labels: ns:pip, prd:pip, add-or-update, rel:pip-account-management-pr-367
