Repository hmcts/pip-account-management, pull requests merged in 2023-02, with the labels that each got.

#194 PUB-1769 MI report enhancement
  src/main/java/uk/gov/hmcts/reform/pip/account/management/database/UserRepository.java
  src/main/java/uk/gov/hmcts/reform/pip/account/management/service/AccountFilteringService.java
  src/test/java/uk/gov/hmcts/reform/pip/account/management/service/AccountFilteringServiceTest.java
Labels: ns:pip, prd:pip, rel:pip-account-management-pr-194

#198 PUB-1783 - Automate updating with base branch
  .github/update-pr.yml
Labels: ns:pip, prd:pip, rel:pip-account-management-pr-198

#197 PUB-1811 - Updated terraform and azure rm
  infrastructure/.terraform-version
  infrastructure/providers.tf
Labels: ns:pip, prd:pip, add-or-update, rel:pip-account-management-pr-197

#192 PUB-1669 Audit table API
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/AuditTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/model/CustomPageImpl.java
  src/main/java/uk/gov/hmcts/reform/pip/account/management/controllers/AuditController.java
  src/main/java/uk/gov/hmcts/reform/pip/account/management/database/AuditRepository.java
  src/main/java/uk/gov/hmcts/reform/pip/account/management/model/AuditLog.java
  src/main/java/uk/gov/hmcts/reform/pip/account/management/model/AuditLogDto.java
  src/main/java/uk/gov/hmcts/reform/pip/account/management/service/AuditService.java
  src/test/java/uk/gov/hmcts/reform/pip/account/management/controllers/AuditControllerTest.java
  src/test/java/uk/gov/hmcts/reform/pip/account/management/service/AuditServiceTest.java
Labels: ns:pip, prd:pip, rel:pip-account-management-pr-192

#214 Updated suppressions
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:pip, prd:pip, rel:pip-account-management-pr-214
