Repository hmcts/pip-account-management, pull requests merged in 2024-06, with the labels that each got.

#419 PUB-2363 - Add SSO user provenance
  README.md
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/AccountTest.java
  src/main/java/uk/gov/hmcts/reform/pip/account/management/model/PiUser.java
  src/test/java/uk/gov/hmcts/reform/pip/account/management/service/AccountFilteringServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pip/account/management/service/SensitivityServiceTest.java
Labels: ns:pip, prd:pip, rel:pip-account-management-pr-419

#418 PUB-2454 - Update pip-data-models with new list type IAC Daily Cause …
  build.gradle
Labels: ns:pip, prd:pip, rel:pip-account-management-pr-418

#424 Fix pipeline - Updated provider
  infrastructure/providers.tf
Labels: ns:pip, prd:pip, stg/add-or-update, prod/add-or-update, rel:pip-account-management-pr-424

#427 PUB-2490 - Updated jenkins nightly time
  Jenkinsfile_nightly
  config/owasp/suppressions.xml
Labels: ns:pip, prd:pip, rel:pip-account-management-pr-427
