Repository hmcts/pip-account-management, pull requests merged in 2024-02, with the labels that each got.

#395 PUB-1619 - Added fortify
  Jenkinsfile_nightly
  README.md
  build.gradle
  config/fortify-client.properties
Labels: ns:pip, prd:pip, rel:pip-account-management-pr-395

#400 PUB-1619 - Updated pipeline
  Jenkinsfile_nightly
Labels: ns:pip, prd:pip, rel:pip-account-management-pr-400

#399 PUB-2300 Add security to Swagger API
  src/main/java/uk/gov/hmcts/reform/pip/account/management/config/OpenApiConfiguration.java
  src/main/java/uk/gov/hmcts/reform/pip/account/management/controllers/AccountController.java
  src/main/java/uk/gov/hmcts/reform/pip/account/management/controllers/AccountFilteringController.java
  src/main/java/uk/gov/hmcts/reform/pip/account/management/controllers/AuditController.java
  src/main/java/uk/gov/hmcts/reform/pip/account/management/controllers/AzureAccountController.java
  src/main/java/uk/gov/hmcts/reform/pip/account/management/controllers/BulkAccountCreationController.java
  src/main/java/uk/gov/hmcts/reform/pip/account/management/controllers/InactiveAccountManagementController.java
  src/main/java/uk/gov/hmcts/reform/pip/account/management/controllers/MediaApplicationController.java
  src/main/java/uk/gov/hmcts/reform/pip/account/management/controllers/SystemAdminAccountController.java
  src/main/java/uk/gov/hmcts/reform/pip/account/management/controllers/TestingSupportController.java
  src/main/java/uk/gov/hmcts/reform/pip/account/management/controllers/ViewController.java
Labels: ns:pip, prd:pip, rel:pip-account-management-pr-399
