Repository hmcts/pip-account-management, pull requests merged in 2025-06, with the labels that each got.

#525 PUB-2847 Add Court of Appeal (Civil Division) Daily Cause List
  build.gradle
Labels: ns:pip, prd:pip, rel:pip-account-management-pr-525

#534 PUB-2920 - Updated auth checks for endpoints
  src/integrationTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/account/AccountTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/account/SystemAdminB2CAccountTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/subscription/SubscriptionTest.java
  src/main/java/uk/gov/hmcts/reform/pip/account/management/service/AuthorisationService.java
  src/test/java/uk/gov/hmcts/reform/pip/account/management/service/AuthorisationServiceTest.java
Labels: ns:pip, prd:pip, rel:pip-account-management-pr-534

#535 PUB-2883 - Update UT IAC regional lists
  build.gradle
Labels: ns:pip, prd:pip, rel:pip-account-management-pr-535
