Repository hmcts/pip-account-management, pull requests merged in 2025-05, with the labels that each got.

#490 PUB-2729 Give Permission To SDP View
  infrastructure/tf-db-flexible.tf
Labels: ns:pip, prd:pip, stg/destroy, prod/destroy, rel:pip-account-management-pr-490

#524 PUB-2817 - Updated dependencies
  build.gradle
  config/owasp/suppressions.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  infrastructure/.terraform-version
  infrastructure/providers.tf
Labels: ns:pip, prd:pip, stg/add-or-update, prod/add-or-update, rel:pip-account-management-pr-524

#520 PUB-2846 Add RCJ list types
  build.gradle
Labels: ns:pip, prd:pip, rel:pip-account-management-pr-520
