Repository hmcts/pip-account-management, pull requests merged in 2025-01, with the labels that each got.

#472 PUB-2712 Add CIC Daily Hearing List
  build.gradle
Labels: ns:pip, prd:pip, rel:pip-account-management-pr-472

#476 Merge Freeze to Master
  Jenkinsfile_CNP
  README.md
  src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/BulkAccountTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/FunctionalAccountControllerTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/FunctionalAccountFilteringControllerTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/FunctionalAzureAccountControllerTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/InactiveAccountsManagementTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/MediaApplicationCreationTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/SystemAdminAccountCreationTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/SystemAdminB2CAccountCreationTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/utils/AccountHelperBase.java
  src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/utils/CustomPageImpl.java
  src/functionalTest/java/uk/gov/hmcts/reform/pip/account/management/utils/FunctionalTestBase.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/account/management/config/AzureBlobConfigurationTestConfiguration.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/account/management/config/AzureConfigurationClientTestConfiguration.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/account/management/config/SwaggerPublisherTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/AccountTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/AuditTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/AzureAccountTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/BulkAccountCreationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/CustomAccountRetrievalTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/GetWelcomeTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/InactiveAccountManagementTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/MediaApplicationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/SensitivityTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/SystemAdminAccountTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/SystemAdminB2CAccountTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/TestingSupportApiTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/ViewTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/account/management/utils/IntegrationBasicTestBase.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/account/management/utils/IntegrationTestBase.java
  src/integrationTest/resources/application-integration-basic.yaml
  src/main/java/uk/gov/hmcts/reform/pip/account/management/config/AzureBlobConfiguration.java
  src/main/java/uk/gov/hmcts/reform/pip/account/management/config/AzureConfigurationClient.java
  src/main/java/uk/gov/hmcts/reform/pip/account/management/config/PersistenceConfiguration.java
Labels: ns:pip, prd:pip, rel:pip-account-management-pr-476

#469 PUB-2693 - Updated dependencies
  build.gradle
  config/owasp/suppressions.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  infrastructure/.terraform-version
  infrastructure/providers.tf
  src/integrationTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/AccountTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/AuditTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/BulkAccountCreationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/SystemAdminB2CAccountTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/account/management/controllers/TestingSupportApiTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/account/management/utils/IntegrationBasicTestBase.java
  src/integrationTest/java/uk/gov/hmcts/reform/pip/account/management/utils/IntegrationTestBase.java
  src/main/resources/application.yaml
Labels: ns:pip, prd:pip, stg/add-or-update, prod/add-or-update, rel:pip-account-management-pr-469

#471 PUB-2706 - Non Strategic Publishing
  build.gradle
Labels: ns:pip, prd:pip, rel:pip-account-management-pr-471

#478 PUB-2720 Update non strategic list names
  build.gradle
Labels: ns:pip, prd:pip

#477 PUB-2702 Update dependencies
  build.gradle
  config/owasp/suppressions.xml
  gradle/wrapper/gradle-wrapper.properties
  infrastructure/.terraform-version
  infrastructure/providers.tf
Labels: ns:pip, prd:pip, stg/add-or-update, prod/add-or-update

#479 PUB-2742 Update and Add UT IAC Lists
  build.gradle
Labels: ns:pip, prd:pip, rel:pip-account-management-pr-479
